version: "3"

services:

  microservice_wb:
    image: registry.ecompl.ru/microservice_wb:latest
    restart: always
    container_name: microservice_wb
    hostname: microservice_wb
    env_file:
      - .env
    ports:
      - 0.0.0.0:${PORT_WEB_APP}:${PORT_WEB_APP}
    networks:
      - ecom_network
    extra_hosts:
      - "db:10.16.0.2"
      - "rabbit:172.17.0.1"
    volumes:
      - ./logs:/home/ecom_ms_wb/logs

networks:
 ecom_network:
   external: true
